/**:
  ros__parameters:
    dispersion_max_range: 3.5 # 1.2 on turtle,  # max range: 3500mm
    dispersion_min_range: 0.12                # min range: 120mm
    dispersion_front_attraction: 1.0
    dispersion_threshold: 1
    dispersion_stop_if_alone: True
    dispersion_allow_dynamic_max_range_setting: False
    max_translational_velocity: 0.26 # max: 0.26 m/s
    max_rotational_velocity: 1.82    # max: 1.82 rad/s
